### ISSUE TITLE
First issue haha :D

### ISSUE THREAD

**Issue by vmario89** [ochorocho/syspass-firefox#1]
HI,
really cool that you began some effort to work on this plugin. I got the github message and installed it. Now i got some questions :)

![grafik](https://user-images.githubusercontent.com/5631071/72248293-20b2bb80-35f7-11ea-954b-7d246f268af6.png)

small feature request: give some visual feedback at "Save preferences". When clicking the button the addon should validate if token and password are fine. Some small popup info would be good aboud "failed/success".

another question: what url do i have to enter? do i need to enter the full API url or just the base url?

third question: what type of API token action to i need to make it work?
![grafik](https://user-images.githubusercontent.com/5631071/72248426-6e2f2880-35f7-11ea-9c97-34c6f1cfc7c4.png)

best regards and thanks for the community work, Mario

**Comment by ochorocho** [comment]
> give some visual feedback at "Save preferences".

Sure, makes sense :-)

> what url do i have to enter?

Something like this `http://demo.syspass.org/`

> what type of API token action to i need to make it work?

"Search Account" and "View Password" with the same password. Not sure if this was a good idea. What do yu think? I thought its a smart move coz tokens are already always the same for a user.

![Bildschirmfoto 2020-01-13 um 09 33 09](https://user-images.githubusercontent.com/4623070/72248616-e39af900-35f7-11ea-89a3-651456400113.png)

**Comment by ochorocho** [comment]
In version 1.1.0

* Added visual feedback
* Updated readme and addon page with config information

**Comment by vmario89** [comment]
hi, thanks for the quick information and the commits. maybe the "save preferences" button could deal with a (curl?) check if the API call returns successful state to validate everything technically.

i updated to 1.1.0 and created the two api actions with same token and same password. 
if i go to some URL where syspass got some password for, nothing occurs on the fields of the form. how to use it? =)

i got some account stored for https://www.buhl.de/mein-buhlkonto/ for example
![grafik](https://user-images.githubusercontent.com/5631071/72303576-0536c780-366e-11ea-9c84-5a639d3afa0d.png)

is there some special syspass button in firefox menu bar which i am not able to find, or should it show some popup like firefox itself does with its own regular firefox:sync tool? like this:
![grafik](https://user-images.githubusercontent.com/5631071/72303648-2f888500-366e-11ea-9599-558c40aa470c.png)


cheers, Mario

**Comment by ochorocho** [comment]
> hi, thanks for the quick information and the commits. maybe the "save preferences" button could deal with a (curl?) check if the API call returns successful state to validate everything technically

Yep, will try to send a request when credentials are save and respond to this

> i got some account stored for https://www.buhl.de/mein-buhlkonto/ for example

The thing is i'm currently not selecting that input field (name="eml-user")
See:
https://github.com/ochorocho/syspass-firefox/blob/master/syspass.js#L157-L163

A solution to this problem could be:

* Find the Password field (type="password")
* Go up in DOM till hit the form tag
* look for the first field within the form.

What do you think? Good or bad? :-)

Thanks for your response.

**Comment by vmario89** [comment]
Hi,
had some time to test a little bit more. Got it working now! :-) It works fine for many pages. A lot do not work yet too . I think i will need to update my syspass URLs in Accounts to be more precise with the saved information. Plus the dom parsing you mention. It works well for pages where i did not store a password in firefox yet or if i run a fresh portable FireFox.

The extension does not properly work in parallel to the built-in firefox password saving mechanism which i use for private needs. If i click into a username field i get some infinite loading bar with graphical offset:

![grafik](https://user-images.githubusercontent.com/5631071/72684568-f888f800-3ae1-11ea-9877-2bab2a7b550a.png)
![grafik](https://user-images.githubusercontent.com/5631071/72684589-2110f200-3ae2-11ea-952f-78c32907aa01.png)
![grafik](https://user-images.githubusercontent.com/5631071/72684601-4998ec00-3ae2-11ea-9192-b6b1fc992374.png)

I think thats my special problem because i have a lot of private passwords stored in firefox/keepass as well as syspass instance for our organization which stores accounts for online shops and so on. So i have multiple sources of passwords. For me it makes no sense to store private passwords into the organizations syspass instance. And it wont make sense to copy/paste the organizations password from syspass to another location. So i will need to those sources run in parallel. Hmmm

**Comment by ochorocho** [comment]
Thanks for the detailed report. I'll check if i can offer an alternative option so select the Passwort. Maybe simply position the suggested password somewhere else.

Btw, uploaded a new version. This is now working in Firefox, Chrome and Edge chromium

**Comment by vmario89** [comment]
Hi,
 just updated. The bug with the spinner disappeared. Thanks for that quick fix. You are just diligent =)

**Comment by vmario89** [comment]
By the way i will close that issue to allow more streamlining of issues. Don't want to blow different topics/issues with that issue. cheers^^
